export const SATUS_CODE_CREATED = 201;
export const SPACE_ASCII_CHAR_NUMBERS = 31
export const ZERO_ASCII_CHAR_NUMBERS = 48
export const NINE_ASCII_CHAR_NUMBERS = 57
export const PREFIJO_REGISTRO = "REG-"
export const PREFIJO_PERFIL_DEPORTIVO = "PER-"